### ISSUE TITLE
Uncaught TypeError: this.editor.on is not a function

### ISSUE THREAD

**Issue by rhutikcodes** [Jisuanke/CodeMirror-Record#39]
Uncaught TypeError: this.editor.on is not a function
    at CodeRecord.listen (CodeRecord.js:45:1)
    at checkCode (App.jsx:13:1)
    at onClick (App.jsx:71:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js:8299:1)
    at react-dom.development.js:8508:1
    at batchedEventUpdates$1 (react-dom.development.js:22396:1)
    at batchedEventUpdates (react-dom.development.js:3745:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507:1)
    at attemptToDispatchEvent (react-dom.development.js:6005:1)
    at dispatchEvent (react-dom.development.js:5924:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at discreteUpdates$1 (react-dom.development.js:22413:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)
listen @ CodeRecord.js:45
checkCode @ App.jsx:13
onClick @ App.jsx:71
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889

**Comment by haoranyu** [comment]
Sorry to reply you so late. Is the problem solved already or not?

If the problem has not been solved, can you tell me the version you are using and show me some code snippet? Events are supported only on 1.1.0+

**Comment by rhutikcodes** [comment]
Hello 👋  No, still getting the same error. I am using 1.1.2

**Comment by rhutikcodes** [comment]
do you have any react app example? Also the demo is not working https://codemirror-record.haoranyu.com/demo/

**Comment by haoranyu** [comment]
> do you have any react app example? Also the demo is not working https://codemirror-record.haoranyu.com/demo/

I only have tried to make it work with vue app. I have not yet tried any react app. However, it should work fine with react since codemirror-record library is a vanilla js library.

Thanks for pointing out the problem of the demo. Some CDN file URL is out-of-date. I am going to update them.

**Comment by haoranyu** [comment]
Considering that there is no further feedback, this issue is closed.
